### ISSUE TITLE
Compatible with "char"?

### ISSUE THREAD

**Issue by ZebNZ** [EinarArnason/ArduinoQueue#15]
Hi all,

Can I use this queue library with char variables instead of int variable?

Thanks,

Zeb

**Comment by EinarArnason** [comment]
It's a template so you just declare the type within the angle brackets. Like so:
```c++
ArduinoQueue<char>
```

**Comment by ZebNZ** [comment]
Thanks @EinarArnason that's really good, but how do I copy what's been dequeued into a char variable?

In your example it is:
`int value = intQueue.dequeue();`
If I do this
`char value[] = intQueue.dequeue();`
it gives this error
`initializer fails to determine size of 'value'`
And if I do this
`char value[10] = intQueue.dequeue();`
it gives this error
`array must be initialized with a brace-enclosed initializer`

Thanks,

Zeb

**Comment by ZebNZ** [comment]
@EinarArnason here is all my code, as you can probably tell, I am getting a lot of errors.

```
/*
        Author: Vasco Baptista
        email: vascojdb@gmail.com
        An example of using Einar Arnason's queue
        In this example we create a queue of int's
        limited by the maximum amount of items
        Usage and further info:
        https://github.com/EinarArnason/ArduinoQueue
*/

#include "Queue.h"

#define QUEUE_SIZE_ITEMS 10

// Queue creation:
ArduinoQueue<char> charQueue(QUEUE_SIZE_ITEMS);

void printQueueStats() {
  Serial.println("");
  Serial.printf("Size of each element:    %u bytes\r\n", charQueue.item_size());
  Serial.printf("Items in queue now:      %u items\r\n", charQueue.item_count());
  Serial.printf("Queue actual max items:  %u items\r\n",
                charQueue.maxQueueSize());
  Serial.printf("Queue actual max memory: %u bytes\r\n",
                charQueue.maxMemorySize());
  Serial.println("");
}

void setup() {
  Serial.begin(115200);
  Serial.println("");
  Serial.println("========== Queue example ==========");
  Serial.printf("Desired max item size:  %u items\r\n", QUEUE_SIZE_ITEMS);
  Serial.println("===================================");
}

void loop() {
  printQueueStats();

  // Add elements: (add more than the queue size for demo purposes)
  if (!charQueue.isFull()) {
    char n[] = "1";
    Serial.printf("Adding value: %i\r\n", n);
    charQueue.enqueue(n);
  }

  printQueueStats();

  if (!charQueue.isEmpty()) {
    char value[] = intQueue.dequeue();
    Serial.printf("Removed value: %i\r\n", value);
  }
  else {
    Serial.println("Queue is empty!");
  }

  printQueueStats();

  // Loop forever
  while (true) {
#ifdef ESP8266
    ESP.wdtFeed();
#endif
  }
}
```

**Comment by EinarArnason** [comment]
You have a few problems there.

Firstly, queuing a local char array won't work as it will be destroyed when the function returns and goes out of scope. You can however queue a single char character, like:
```c++
queue.enqueue('1');
```
but if you are queuing strings, you will have dynamically allocate it with the new operator and enqueue a char*.  Using a string library would make things alot easier, unless you really want to do low level stuff. If the array is not a string, you need to queue an enclosed object with information about the size of the array as it has no way of knowing how large an array is from a pointer alone. That's the reason why 
```c++
char value[] = intQueue.dequeue();
```
wont work. An array must have predetermined size. For strings You could do something like this:
```c++
char value[200];
strcpy(value, queue.dequeue());
```
Using a big enough buffer you know won't max out. Because strings end with a null character ('\0'). Otherwise, a size must be known.

What the queue library does really is storing base types (int, char, bool, double, etc...) and pointers.

**Comment by ZebNZ** [comment]
Sweet, thanks very much for your help!
